name: Trunk
on:
  push:
    branches: ["trunk"]
  pull_request:
    branches: ["trunk"]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Start Docker
      run: make start-docker

    - name: Prepare Web Application
      run: make prepare-app

    - name: Maven Package
      run: mvn --batch-mode --update-snapshots package
